function triangles = icosahedron()
    % icosahedron: returns the vertices of a regular icosahedron centered inscribed in a unit sphere.
    %
    % Output:
    %   triangles: the vertices of the icosahedron, as a 3x60 matrix, containing along its columns,
    %              the unit vectors of the triangles. Each group of three columns corresponds to a triangle.

    phi = (1 + sqrt(5)) / 2; % Golden ratio

    points = [
              -1, phi, 0;
              1, phi, 0;
              -1, -phi, 0;
              1, -phi, 0;
              0, -1, phi;
              0, 1, phi;
              0, -1, -phi;
              0, 1, -phi;
              phi, 0, -1;
              phi, 0, 1;
              -phi, 0, -1;
              -phi, 0, 1
              ]';

    triangles_idx = [1, 6, 2, ...
                         1, 2, 8, ...
                         1, 12, 6, ...
                         1, 8, 11, ...
                         1, 11, 12, ...
                         2, 6, 10, ...
                         2, 9, 8, ...
                         2, 10, 9, ...
                         3, 4, 5, ...
                         3, 7, 4, ...
                         3, 5, 12, ...
                         3, 11, 7, ...
                         3, 12, 11, ...
                         4, 10, 5, ...
                         4, 7, 9, ...
                         4, 9, 10, ...
                         5, 10, 6, ...
                         5, 6, 12, ...
                         7, 8, 9, ...
                         7, 11, 8];

    triangles = points(:, triangles_idx);
    triangles = triangles ./ vecnorm(triangles); % Normalize to lie on the unit sphere
end
